// ── Offer drawer deep-dive content ──
export const drawerData = {
  fr: [
    {
      id: 'essentiel', icon: '🛡️', name: 'Essentiel', price: '400 DH', subtitle: 'Le bouclier de base',
      story: "Un filtre invisible sur votre connexion. Dès qu'un appareil de vos enfants essaie d'ouvrir un site pour adultes, un jeu d'argent ou une page malveillante, le routeur le bloque avant même que la page se charge. Vos enfants ne voient rien. Vous ne faites rien.",
      stepsTitle: "Comment ça marche chez vous",
      steps: ["Câble RJ45 derrière votre box", "Les enfants rejoignent le Wi-Fi 'Maison_Enfants'", "Tout contenu dangereux est bloqué automatiquement, 24h/24"],
      checkTitle: "Inclus dans cette offre",
      checklist: ["Filtrage DNS OpenDNS FamilyShield (85M+ sites bloqués)", "Réseau Wi-Fi enfants séparé du vôtre", "Blocage malwares et phishing avant chargement", "Compatible Maroc Telecom, Orange, Inwi", "Support WhatsApp 7j/7", "Garantie échange 30 jours", "Guide d'installation illustré inclus", "Fonctionne sur tout appareil connecté (tablettes, téléphones, PC)"],
      idealTitle: "Idéal si…",
      ideal: ["Enfants de 6–12 ans", "Vous voulez bloquer les contenus dangereux sans complication", "Premier achat de contrôle parental"],
      limitsTitle: "Ce que cette offre ne fait PAS",
      limits: ["Ne gère pas les horaires d'écran", "Ne bloque pas les réseaux sociaux spécifiquement"],
      cta: "Commander via WhatsApp", close: "Fermer",
    },
    {
      id: 'couvrefeu', icon: '⏰', name: 'Couvre-feu', price: '480 DH', subtitle: 'Fini les batailles du soir',
      story: "Chaque soir à 22h pile, le Wi-Fi de vos enfants s'éteint. Automatiquement. Sans confisquer un téléphone, sans conflit. Les règles sont dans le routeur — pas dans votre tête.",
      stepsTitle: "Comment ça marche chez vous",
      steps: ["Vous choisissez vos horaires lors de la commande", "Le routeur applique les coupures chaque jour automatiquement", "Modification des horaires via WhatsApp à tout moment"],
      checkTitle: "Inclus dans cette offre",
      checklist: ["Tout l'Essentiel inclus", "Coupure automatique Wi-Fi enfants à l'heure de votre choix", "Plage 'Heures de devoirs' configurée (ex. 18h–20h)", "Horaires semaine / week-end différenciables", "Modification des horaires à distance via WhatsApp (sous 24h, inclus)", "Aucune intervention de votre part au quotidien"],
      idealTitle: "Idéal si…",
      ideal: ["Enfants qui restent sur écrans jusqu'à minuit", "Parents qui rentrent tard et ne peuvent pas surveiller", "Vous voulez imposer des règles sans conflit quotidien"],
      limitsTitle: "Ce que cette offre ne fait PAS",
      limits: ["Ne bloque pas les réseaux sociaux spécifiquement (voir Anti-Distraction)", "Ne fonctionne pas si l'enfant coupe le Wi-Fi et utilise la 4G"],
      cta: "Commander via WhatsApp", close: "Fermer",
    },
    {
      id: 'anti', icon: '📚', name: 'Anti-Distraction', price: '530 DH', subtitle: 'Internet utile, sans le superflu',
      story: "Votre enfant a besoin d'internet pour ses devoirs — mais dès qu'il ouvre TikTok, les deux heures de travail partent en fumée. Ce mode bloque les réseaux sociaux et les jeux pendant les heures d'études, mais laisse Google, Wikipedia et YouTube éducatif complètement ouverts.",
      stepsTitle: "Comment ça marche chez vous",
      steps: ["Vous indiquez vos horaires d'études lors de la commande", "Réseaux sociaux et jeux bloqués pendant ces horaires", "Mode Études activable/désactivable à tout moment via WhatsApp"],
      checkTitle: "Inclus dans cette offre",
      checklist: ["Tout le Couvre-feu inclus", "Blocage TikTok, Instagram, Snapchat, Roblox, Facebook", "Google, Wikipedia, YouTube Éducatif, Duolingo restent accessibles", "Mode Études activable à la demande", "Profil ado configuré pour 13–17 ans", "Ajout de sites à bloquer ou débloquer sur demande (inclus)"],
      idealTitle: "Idéal si…",
      ideal: ["Ados de 13–17 ans", "Notes qui baissent à cause des réseaux sociaux", "Différencier internet scolaire et internet loisir"],
      limitsTitle: "Ce que cette offre ne fait PAS",
      limits: ["Ne fonctionne pas en 4G si l'enfant coupe le Wi-Fi", "YouTube filtré en mode études : contenus éducatifs accessibles, autres bloqués sur demande"],
      cta: "Commander via WhatsApp", close: "Fermer",
    },
    {
      id: 'maison', icon: '🏠', name: 'Pack Maison', price: '750 DH', subtitle: 'Pour les grandes maisons',
      story: "La chambre de votre fils est au 2ème étage et le Wi-Fi n'y arrive pas ? Il utilise ses données mobiles où votre routeur ne le rejoint pas. Avec le Pack Maison, deux boîtiers configurés ensemble couvrent toute la maison — et notre technicien vient tout installer chez vous.",
      stepsTitle: "Comment ça marche chez vous",
      steps: ["Livraison des 2 boîtiers configurés ensemble", "Installation à domicile par notre technicien (Tanger, 30 km max)", "Test de chaque appareil enfant sur site avant départ"],
      checkTitle: "Inclus dans cette offre",
      checklist: ["Tout l'Anti-Distraction inclus", "Routeur DarBox principal + répéteur mesh préconfiguré", "Couverture Wi-Fi protégé sur toute la surface de la maison", "Installation VIP à domicile (Tanger et environs, rayon 30 km)", "Configuration selon le plan de votre maison", "Test de chaque appareil enfant sur site", "Support prioritaire post-installation"],
      idealTitle: "Idéal si…",
      ideal: ["Maison de 2 étages ou grande surface", "Chambre enfant loin du salon", "Vous préférez une installation clé en main"],
      limitsTitle: "Ce que cette offre ne fait PAS",
      limits: ["Ne couvre pas les appareils connectés en 4G externe"],
      cta: "Commander via WhatsApp", close: "Fermer",
    },
    {
      id: 'config', icon: '💡', name: 'Service Config', price: '150–200 DH', subtitle: 'Vous avez déjà un routeur ? On le configure.',
      story: "Vous avez déjà un bon routeur chez vous — un modèle récent acheté chez Maroc Telecom ou un équipement de qualité. Vous n'avez pas besoin d'en acheter un nouveau. Notre technicien se connecte à distance (ou vient chez vous) et programme directement votre routeur existant avec exactement les mêmes protections DNS, pare-feu et couvre-feu. Même résultat. Aucun achat matériel.",
      stepsTitle: "Comment ça marche",
      steps: ["À distance : accès via TeamViewer (guidé), config ~45 min", "À domicile : rendez-vous, config complète ~1h, test sur place", "Mise à jour ultérieure : 80 DH"],
      checkTitle: "Inclus",
      checklist: ["Config à distance (150 DH) : DNS + pare-feu + couvre-feu, ~45 min, compatible routeurs 2018+", "Config à domicile (200 DH) : tout le remote + déplacement + config personnalisée", "Si routeur non compatible → orientation vers l'offre Essentiel sans frais", "Reconfiguration ultérieure : 80 DH"],
      idealTitle: "Idéal si…",
      ideal: ["Vous avez déjà un routeur performant", "Budget limité", "Vous voulez tester avant d'investir dans du matériel"],
      limitsTitle: "Ce que ce service ne fait PAS",
      limits: ["Non disponible pour routeurs basiques fournis par les opérateurs (box Maroc Telecom standard)"],
      cta: "Demander un devis sur WhatsApp", close: "Fermer",
    },
  ],
  en: [
    {
      id: 'essentiel', icon: '🛡️', name: 'Essential', price: '400 MAD', subtitle: 'The basic shield',
      story: "Imagine an invisible filter on your internet connection. Whenever your child's device tries to open an adult site, a gambling page, or a malicious link, the router blocks it before the page even loads. Your children see nothing. You do nothing. It works on its own, 24/7.",
      stepsTitle: "How it works at home",
      steps: ["RJ45 cable behind your box", "Kids connect to 'Maison_Enfants' Wi-Fi", "All dangerous content is blocked automatically"],
      checkTitle: "Included in this plan",
      checklist: ["OpenDNS FamilyShield filtering (85M+ blocked sites)", "Kids Wi-Fi network completely separate from yours", "Malware & phishing blocked before loading", "WhatsApp support 7/7", "30-day exchange guarantee", "Illustrated installation guide included", "Works on tablets, phones, PCs, any connected device"],
      idealTitle: "Ideal if…",
      ideal: ["Children aged 6–12", "You just want to block dangerous content without hassle", "First parental control purchase"],
      limitsTitle: "What this plan does NOT do",
      limits: ["Does not manage screen time schedules", "Does not specifically block social media"],
      cta: "Order via WhatsApp", close: "Close",
    },
    {
      id: 'couvrefeu', icon: '⏰', name: 'Curfew', price: '480 MAD', subtitle: 'No more bedtime battles',
      story: "Every evening at 10PM sharp, your children's Wi-Fi turns off. Automatically. Without you saying a word, confiscating a phone, or entering a conflict. During homework hours — say 6PM to 8PM — same thing: internet off for kids, untouched for you. The rules are in the router, not in your head.",
      stepsTitle: "How it works at home",
      steps: ["You choose your schedules when ordering", "The router applies shutdowns automatically every day", "Schedule changes anytime via WhatsApp"],
      checkTitle: "Included in this plan",
      checklist: ["Everything in Essential included", "Automatic kids Wi-Fi shutdown at your chosen time", "'Homework hours' slot configured (e.g., 6PM–8PM)", "Different schedules possible weekday/weekend", "Remote schedule changes via WhatsApp (within 24h, included)", "Zero daily intervention from you"],
      idealTitle: "Ideal if…",
      ideal: ["Kids who stay on screens until midnight", "You want to enforce rules without conflict", "Parents who come home late and can't supervise"],
      limitsTitle: "What this plan does NOT do",
      limits: ["Does not specifically block social media (see Anti-Distraction)", "Does not work on 4G if the child disables Wi-Fi"],
      cta: "Order via WhatsApp", close: "Close",
    },
    {
      id: 'anti', icon: '📚', name: 'Anti-Distraction', price: '530 MAD', subtitle: 'Useful internet, zero fluff',
      story: "Your child needs the internet for homework. But the moment they open 'TikTok', two hours of work go up in smoke. This mode blocks TikTok, Instagram, Snapchat, and Roblox during study hours — but leaves Google, Wikipedia, Educational YouTube, and all school platforms fully accessible. Useful internet. Zero fluff.",
      stepsTitle: "How it works at home",
      steps: ["You specify study hours when ordering", "During those hours: social media & games blocked, school internet intact", "Study Mode activatable anytime via WhatsApp request"],
      checkTitle: "Included in this plan",
      checklist: ["Everything in Curfew included", "Blocks TikTok, Instagram, Snapchat, Roblox, Facebook", "Google, Wikipedia, Educational YouTube, Duolingo remain accessible", "Study Mode toggleable on demand", "Teen profile configured for ages 13–17", "Add sites to block or unblock on request (included)"],
      idealTitle: "Ideal if…",
      ideal: ["Teens aged 13–17", "Grades dropping due to social media", "You want to separate school internet from leisure internet"],
      limitsTitle: "What this plan does NOT do",
      limits: ["Does not block 4G access if the child uses mobile data", "Non-educational YouTube remains partially accessible (unless specifically requested)"],
      cta: "Order via WhatsApp", close: "Close",
    },
    {
      id: 'maison', icon: '🏠', name: 'Home Pack', price: '750 MAD', subtitle: 'For large homes',
      story: "Your son's room is on the 2nd floor. The box Wi-Fi barely reaches there — so he uses mobile data where your router can't follow. With the Home Pack, you get two devices configured together: the main router and a mesh access point that extends protection to every room, even upstairs, even the terrace. And our technician installs everything at your home.",
      stepsTitle: "How it works at home",
      steps: ["Delivery of 2 pre-configured devices", "Merouan comes to your home for installation (Tangier area)", "Full test of every device in front of you before leaving"],
      checkTitle: "Included in this plan",
      checklist: ["Everything in Anti-Distraction included", "Main DarBox router + pre-configured mesh repeater", "Protected Wi-Fi coverage over entire house", "VIP home installation by our technician", "Custom config based on your house layout", "On-site test of each child's device", "Priority post-installation support"],
      idealTitle: "Ideal if…",
      ideal: ["2-story house or large area", "Child's room far from the living room", "You prefer turnkey installation without touching anything yourself"],
      limitsTitle: "What this plan does NOT do",
      limits: ["Does not cover devices connected via external 4G"],
      cta: "Order via WhatsApp", close: "Close",
    },
    {
      id: 'config', icon: '💡', name: 'Config Service', price: '150–200 MAD', subtitle: 'Already have a router? We configure it.',
      story: "You already have a good router at home — a recent model or quality equipment. You don't need to buy a new one. Our technician connects remotely (or comes to your home) and programs your existing router with the same DNS protections, firewall, and curfew. Same result. No hardware purchase.",
      stepsTitle: "How it works",
      steps: ["Remote: access via TeamViewer (guided), config ~45 min", "On-site: home visit, full config ~1h, on-site testing", "Later updates: 80 MAD"],
      checkTitle: "Included",
      checklist: ["Remote config (150 MAD): DNS + firewall + curfew, ~45 min, compatible with most 2018+ routers", "On-site config (200 MAD): everything remote + home visit + custom config", "If router not compatible → guidance to Essential plan at no charge", "Later reconfiguration: 80 MAD"],
      idealTitle: "Ideal if…",
      ideal: ["You already have a capable router", "Limited budget", "You want to test before investing in hardware"],
      limitsTitle: "What this service does NOT do",
      limits: ["Not available for basic operator-provided routers (standard Maroc Telecom box)"],
      cta: "Request a quote on WhatsApp", close: "Close",
    },
  ],
  ar: [
    {
      id: 'essentiel', icon: '🛡️', name: 'أساسي', price: '400 درهم', subtitle: 'الدرع الأساسي',
      story: "تخيّل فلتر خفي على اتصالك بالإنترنت. كلما حاول جهاز طفلك فتح موقع للبالغين أو صفحة خبيثة، الراوتر يحجبه قبل ما الصفحة تتحمّل حتى. أطفالك ما يشوفو والو. نتا ما دير والو. خدّام بوحدو 24/7.",
      stepsTitle: "كيفاش خدّام عندك فالدار",
      steps: ["كابل RJ45 ورا البوكس ديالك", "الأطفال يتصلو بـ Wi-Fi 'Maison_Enfants'", "كل محتوى خطير محجوب تلقائياً"],
      checkTitle: "مشمول في هاد العرض",
      checklist: ["فلترة DNS OpenDNS FamilyShield (85+ مليون موقع محجوب)", "شبكة Wi-Fi ديال الأطفال منفصلة تماماً عن ديالك", "حجب البرمجيات الخبيثة والتصيد قبل التحميل", "دعم واتساب 7/7", "ضمان استبدال 30 يوم", "دليل تثبيت مصوّر مرفق", "خدّام على التابلت، التليفون، الكمبيوتر، أي جهاز"],
      idealTitle: "مثالي إلا…",
      ideal: ["أطفال من 6 لـ 12 سنة", "بغيتي غير تحجب المحتوى الخطير بلا ما تعقّد راسك", "أول مرة تشري رقابة أبوية"],
      limitsTitle: "شنو ما يديرش هاد العرض",
      limits: ["ما يتحكمش فأوقات الشاشة", "ما يحجبش وسائل التواصل بشكل خاص"],
      cta: "اطلب عبر واتساب", close: "إغلاق",
    },
    {
      id: 'couvrefeu', icon: '⏰', name: 'حظر تجول', price: '480 درهم', subtitle: 'سالات المعارك الليلية',
      story: "كل ليلة على 10 الليل بالضبط، الـ Wi-Fi ديال أطفالك يطفا. أوتوماتيكياً. بلا ما تهضر كلمة، بلا ما تصادر تليفون، بلا ما تدخل فصراع. وفي ساعات الفروض — مثلاً من 6 لـ 8 — نفس الشي: الأنترنت مقطوع على الأطفال، وشغال عندك نتا. القواعد فالراوتر. ماشي فراسك.",
      stepsTitle: "كيفاش خدّام عندك فالدار",
      steps: ["نتا تختار الأوقات ملي تطلب", "الراوتر يطبّق القطع كل يوم أوتوماتيكياً", "تبديل الأوقات عبر واتساب أي وقت"],
      checkTitle: "مشمول في هاد العرض",
      checklist: ["كلشي ديال الأساسي مشمول", "قطع Wi-Fi تلقائي للأطفال فالوقت لّي تختار", "وقت 'ساعات الفروض' مُعدّ (مثلاً 18h–20h)", "أوقات مختلفة ممكنة أسبوع/ويكند", "تعديل الأوقات عن بُعد عبر واتساب (خلال 24 ساعة، مشمول)", "والو ما تدير كل يوم"],
      idealTitle: "مثالي إلا…",
      ideal: ["أطفال يبقاو على الشاشات حتى نص الليل", "بغيتي تفرض قواعد بلا صراع", "الوالدين لّي يرجعو معطّلين وما يقدروش يراقبو"],
      limitsTitle: "شنو ما يديرش هاد العرض",
      limits: ["ما يحجبش وسائل التواصل بشكل خاص (شوف ضد التشتيت)", "ما يخدمش على 4G إلا الطفل طفا الـ Wi-Fi"],
      cta: "اطلب عبر واتساب", close: "إغلاق",
    },
    {
      id: 'anti', icon: '📚', name: 'ضد التشتيت', price: '530 درهم', subtitle: 'أنترنت مفيد، بلا زيادة',
      story: "ولدك محتاج الأنترنت للفروض. ولكن كيف يفتح TikTok، ساعتين ديال الخدمة طارو. هاد الوضع يحجب تيك توك وإنستغرام وسنابشات وروبلوکس فساعات الفروض — ولكن يخلّي جوجل وويكيبيديا ويوتيوب التعليمي خدّامين. أنترنت مفيد. صفر تشتيت.",
      stepsTitle: "كيفاش خدّام عندك فالدار",
      steps: ["تحدد أوقات الدراسة ملي تطلب", "فداك الأوقات: وسائل التواصل والألعاب محجوبين، الأنترنت المدرسي شغال", "وضع الدراسة يتفعّل أي وقت عبر واتساب"],
      checkTitle: "مشمول في هاد العرض",
      checklist: ["كلشي ديال حظر التجول مشمول", "حجب تيك توك، إنستغرام، سنابشات، روبلوکس، فيسبوك", "جوجل، ويكيبيديا، يوتيوب التعليمي، Duolingo خدّامين", "وضع الدراسة يتفعّل/يتطفا على الطلب", "بروفيل مراهق مُعدّ لـ 13–17 سنة", "إضافة مواقع للحجب أو الفتح على الطلب (مشمول)"],
      idealTitle: "مثالي إلا…",
      ideal: ["مراهقين من 13 لـ 17 سنة", "النقاط نازلين بسبب وسائل التواصل", "بغيتي تفرّق بين أنترنت المدرسة وأنترنت الترفيه"],
      limitsTitle: "شنو ما يديرش هاد العرض",
      limits: ["ما يحجبش 4G إلا الطفل خدم بالبيانات ديالو", "يوتيوب غير التعليمي باقي يخدم جزئياً (إلا طلبتي بشكل خاص)"],
      cta: "اطلب عبر واتساب", close: "إغلاق",
    },
    {
      id: 'maison', icon: '🏠', name: 'باك المنزل', price: '750 درهم', subtitle: 'للمنازل الكبيرة',
      story: "بيت ولدك فالطابق الثاني. الـ Wi-Fi ديال البوكس ما كيوصلش تماه — فهو كيخدم بالبيانات ديالو فين الراوتر ما يقدرش يوصلو. مع باك المنزل، كتستقبل جوج بوآتي مُعدّين مع بعض: الراوتر الرئيسي ونقطة وصول mesh لّي كتمدّ الحماية لكلشي ديال البيت. وتقني ديالنا يجي يركّب كلشي.",
      stepsTitle: "كيفاش خدّام عندك فالدار",
      steps: ["توصيل جوج بوآتي مُعدّين مع بعض", "مروان يجي عندك للتركيب (طنجة والضواحي)", "تجربة كاملة ديال كل جهاز قدّامك قبل ما يمشي"],
      checkTitle: "مشمول في هاد العرض",
      checklist: ["كلشي ديال ضد التشتيت مشمول", "راوتر DarBox رئيسي + مقوّي mesh مُعدّ", "تغطية Wi-Fi محمي على كل مساحة الدار", "تركيب VIP فالدار بواسطة التقني ديالنا", "تكوين مخصص حسب تصميم دارك", "تجربة كل جهاز طفل فالبلاصة", "دعم أولوي بعد التركيب"],
      idealTitle: "مثالي إلا…",
      ideal: ["دار بطابقين أو مساحة كبيرة", "بيت الطفل بعيد عن الصالون", "تفضّل تركيب جاهز بلا ما تمسّ شي حاجة"],
      limitsTitle: "شنو ما يديرش هاد العرض",
      limits: ["ما يغطيش الأجهزة المتصلة بـ 4G الخارجي"],
      cta: "اطلب عبر واتساب", close: "إغلاق",
    },
    {
      id: 'config', icon: '💡', name: 'خدمة التكوين', price: '150–200 درهم', subtitle: 'عندك راوتر؟ نبرمجوه ليك.',
      story: "عندك راوتر مزيان فالدار — موديل جديد ولا تجهيز ديال الجودة. ما محتاجش تشري واحد جديد. التقني ديالنا يتصل عن بُعد (ولا يجي عندك) ويبرمج الراوتر ديالك بنفس الحمايات DNS والجدار الناري وحظر التجول. نفس النتيجة. والو ما تشري.",
      stepsTitle: "كيفاش خدّام",
      steps: ["عن بُعد: وصول عبر TeamViewer (مصحوب)، تكوين ~45 دقيقة", "فالدار: موعد، تكوين كامل ~ساعة، تجربة فالبلاصة", "تحديث لاحق: 80 درهم"],
      checkTitle: "مشمول",
      checklist: ["تكوين عن بُعد (150 درهم): DNS + جدار ناري + حظر تجول، ~45 دقيقة، متوافق مع أغلب الراوترات 2018+", "تكوين فالدار (200 درهم): كلشي ديال عن بُعد + تنقل + تكوين مخصص", "إلا الراوتر ما متوافقش → توجيه للعرض الأساسي بلا مصاريف", "إعادة تكوين لاحقة: 80 درهم"],
      idealTitle: "مثالي إلا…",
      ideal: ["عندك راوتر قوي", "الميزانية محدودة", "بغيتي تجرّب قبل ما تستثمر فالمعدات"],
      limitsTitle: "شنو ما تديرش هاد الخدمة",
      limits: ["غير متاحة للراوترات الأساسية ديال المشغلين (بوكس اتصالات المغرب العادي)"],
      cta: "اطلب تسعيرة عبر واتساب", close: "إغلاق",
    },
  ],
};
